name: Continuos-integration
#el on, funciona como el trigger de azure devops
on:
  push: 
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Cambié a v2, que es la versión estable

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Utiliza la acción correcta para instalar Node.js
        with:
          node-version: '14'  # O la versión de Node.js que prefieras

      - name: Install dependencies
        run: npm install 

      - name: Run project
        run: node index.js
